name: generate-badges
on:
  push:
    branches: [main]
    paths: ['**.java']
jobs:
  generate-badges:
    runs-on: ubuntu-latest
    if: "!contains(github.actor, 'weichbot10')"
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WEICHBOT }}
      - name: setup java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      - run: echo ${{ secrets.ENV }} > .env
      - name: generate report
        run: mvn jacoco:prepare-agent test install jacoco:report
      - name: generate coverage badges
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
      - name: wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'run-tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: download test badge
        run: curl https://img.shields.io/github/workflow/status/weichware-10/util/tests/${GITHUB_REF#refs/heads/}?label=tests > .github/badges/tests.svg
      - name: import GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.WEICHBOT_GPG_PRIVATE }}
          passphrase: ${{ secrets.WEICHBOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[chore] updated badges'
          commit_user_name: 'weichbot10'
          commit_user_email: 'weichbot10@users.noreply.github.com'
