name: create-tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: 'v*.*'
jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: contains('["joshuajeschek, weichbot10"]', github.actor)
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WEICHBOT }}
      - name: setup java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      - name: increase version in pom.xml
        run: mvn versions:set -DnewVersion="${{ github.event.inputs.tag }}"
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: import GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.WEICHBOT_GPG_PRIVATE }}
          passphrase: ${{ secrets.WEICHBOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: pom.xml
          commit_message: '[release] - ${{ github.event.inputs.tag }}'
          commit_user_name: 'weichbot10'
          commit_user_email: 'weichbot10@users.noreply.github.com'
          tagging_message: ${{ github.event.inputs.tag }}
